### ISSUE TITLE
Style is not applied to the FAB button

### ISSUE THREAD

**Issue by carvalhorr** [markormesher/android-fab#11]
When I apply a style in XML to the FAB what gets styled is the clickable area that fills the entire screen. Would it be possible to apply the style to the button instead?

Example:

If I use the style tag:
`<uk.co.markormesher.android_fab.FloatingActionButton style="my_style_here" />`

I get this: 
![device-2017-06-29-233008](https://user-images.githubusercontent.com/3863951/27713323-14079748-5d23-11e7-85c1-c3cceedd2302.png)

**Comment by markormesher** [comment]
Hi @carvalhorr. The problem with styling the `uk.co.markormesher.android_fab.FloatingActionButton` view element is that it's not just the button, it's actually a wrapper that contains the button, the icon, the speed-dial menu components, etc.

What kind of styles were you trying to apply? I can help you figure out how to apply them to just the button (or make plans for a new release that will allow it).

**Comment by carvalhorr** [comment]
Thanks, @markormesher. I would like the same syle that is applied in the other FAB.

The style is defined here: https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values/styles.xml (See the style name "OneBusAway.FloatingActionButton")

**Comment by barbeau** [comment]
@carvalhorr What device/emulator/Android version was the screenshot from?

I had a similar issue when adding the setting for "left hand mode" to OneBusAway Android (https://github.com/OneBusAway/onebusaway-android/commit/625b262accfef0ae3e257c00bc0d844e1b4dfea6), which simply flips the My Location FAB to be aligned to parent left instead of parent right (i.e., moves it to the left side of the screen).  From the above commit description:

> Note that below API Level 17, the FAB gets stretched across the entire screen immediately after changing the setting.  Apparently you can't remove a layout rule programmatically before this (API Level 17), so the only workaround is restarting the app to reset the FAB layout and remove the opposite rule.

It's been a while since I looked at this, so I'm not sure if it's related or not.  But it would be good to know which device/emulator you're seeing this on.

**Comment by carvalhorr** [comment]
This is an emulator running API level 23.

**Comment by markormesher** [comment]
Dragging up an old issue: one thing on my list to add in v2.1 is exposure of the core views making up the FAB (the card view, the icon wrapper, etc). I imagine you've worked around this already, but that should resolve this for anyone coming across this in the future.

**Comment by markormesher** [comment]
Something like this: https://github.com/markormesher/android-fab/compare/expose-underlying-views
