### ISSUE TITLE
To much work in Fragment

### ISSUE THREAD

**Issue by Martindgadr** [markormesher/android-fab#29]
Hi there, I'm trying to implement you library in a project but I found an issue when i'm trying to display a SpeedDialer menu, no only that just when I press click on fab button show me this:

- Skipped 38 frames!  The application may be doing too much work on its main thread.

I'm working on a fragment, don't know if this is part of the issue but it's rare. I Just need to implement a fab with speed dial 2 items, not anymore... so it's an easy implementation.

**Comment by markormesher** [comment]
Hey @Martindgadr, thanks for flagging this. I've set the library up on my phone in a test app using fragments and I wasn't able to reproduce the issue, but I will take a closer look later in the week to see if there are any places the app might be slowing things down. In the meantime, can you confirm that the issue is only caused when using this library, and if possible share the source code of where you're using it? Thanks.

**Comment by objectorientedperson** [comment]
@Martindgadr hi, I have the same issue. Could you manage time to take a look into this?

**Comment by markormesher** [comment]
Hi @objectorientedperson. I wasn't able to reproduce the issue last time and didn't get any code sample or info, so unfortunately there wasn't anything I could do. Could you share the repo or the relevant code fragment that's causing this, and let me know when the issue happens? The more info, the better.

**Comment by markormesher** [comment]
This seems to be inactive, so I'll close this issue. @objectorientedperson or @Martindgadr feel free to re-open it with some example code so I can try to repro it.
