### ISSUE TITLE
Unable  to open speed dial automaticallay

### ISSUE THREAD

**Issue by himgupta** [markormesher/android-fab#40]
Hi,

In my layout I am having recycler view. Initially I put floating action button as hidden I want that whenever i click on any recyclerview item fab should get visible and speed dial menu should open and when after opening the speed dial menu clicking on content cover speed dial menu should first close and then gets hidden. I tried it using an interface to get the click event of recyclerview item and checked for speed dialmenu is opened or not then tried to toggle that.But speed dial menu is not opening it is getting opened all menu items get overlapped.Below is my code.

interface callback:
public void onLongPressed() {
if(floatingActionButton.isSpeedDialMenuOpen()){
floatingActionButton.hide(true);
floatingActionButton.setVisibility(View.GONE);
}else {
floatingActionButton.setVisibility(View.VISIBLE);
floatingActionButton.setContentCoverEnabled(true);
floatingActionButton.setContentCoverColour(0xffff9900);
floatingActionButton.setContentCoverEnabled(true);
floatingActionButton.callOnClick();
}
}
where floatingActionButton is initialised as in onCreate of activity
floatingActionButton = findViewById(R.id.fabMenu);
floatingActionButton.setSpeedDialMenuAdapter(new CustomSpeedMenuAdapter(this));

In layout

<uk.co.markormesher.android_fab.FloatingActionButton
android:id="@+id/fabMenu"
android:visibility="gone"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_marginTop="28dp"
app:buttonBackgroundColour="@color/dashboard1"
app:buttonIcon="@drawable/ic_add"
app:buttonPosition="top|start" />

**Comment by markormesher** [comment]
Hey - sorry, didn't notice this thread! Is the code on GitHub or elsewhere online? I'm not sure I follow exactly what's meant to be happening and what's going wrong. One point is that setting visibility on the FAB shouldn't normally be necessary as you can use the `.hide()` and `.show()` methods.

**Comment by himgupta** [comment]
Changed the code to below but still it is not opening speed dial automatically.

`    public void onLongPressed() {
        if (floatingActionButton.isSpeedDialMenuOpen()) {
            floatingActionButton.hide(true);
        } else {
            floatingActionButton.show();
            floatingActionButton.setContentCoverEnabled(true);
            floatingActionButton.setContentCoverColour(0xffff9900);
            floatingActionButton.setContentCoverEnabled(true);
            floatingActionButton.callOnClick();
        }
}`

**Comment by markormesher** [comment]
Just to make sure I understand fully, this is what you want to achieve:
- The FAB is initially hidden, and you have a RecyclerView of items.
- When a user long-presses on an item, the FAB should become visible and the speed-dial menu should open.
- When someone selects a speed-dial option or clicks outside to close it, the speed-dial menu should close and the FAB should hide.

If that's correct, I'd recommend something like the following:

- When you initialise your view, hide the FAB with the `.hide(true)` method (specifying `true` to hide it without an animation).
  - This is also when you can set the content cover colour, because it will persist between hiding/showing the FAB. You also don't need to set the content cover to enabled, because that's the default anyway.
  - Also at this point, set a listener for when the speed-dial closes using `.setOnSpeedDialMenuCloseListener()`, and have your listener hide the FAB with the `.hide()` method.
- In your long-press listener on the RecyclerView, call the `.show()` method to show the FAB and the `. openSpeedDialMenu()` method to open the speed-dial.
- When a user long-presses an item, the FAB should show up and the speed-dial menu should open, then when they close the menu (by selecting or tapping outside) the FAB should disappear again.

That should achieve what you're looking for (if I've understood correctly), but I want to offer one caveat:  I haven't seen your app and I don't know your use case, but this sounds like an odd user-interaction pattern. FABs are normally used for the primary action in an activity or fragment, but what we're doing here sounds like it would be more suited to a pop-up dialog menu or a context menu.

**Comment by markormesher** [comment]
Hey @himgupta - did you manage to get this sorted?

**Comment by markormesher** [comment]
This seems to be inactive, so I'll close this issue. @himgupta feel free to re-open it if you need to.
