### ISSUE TITLE
How to change menu items background color? 

### ISSUE THREAD

**Issue by edu1525** [markormesher/android-fab#43]
Is it possible to change the color of menu items?

**Comment by markormesher** [comment]
It sure is! The `onPrepareXYZ()` methods [here](https://github.com/markormesher/android-fab/blob/development/fab/src/main/kotlin/uk/co/markormesher/android_fab/SpeedDialMenuAdapter.kt#L42-L60) give you access to the views that make up the speed-dial menu items _after_ they are generated but _before_ they are added to the view, so that is where you can change anything you want about them.
